// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDAutomation.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("BasicPlanSigin")]
    [NUnit.Framework.CategoryAttribute("Smoke")]
    public partial class BasicPlanSiginFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BasicPlanSigin.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BasicPlanSigin", null, ProgrammingLanguage.CSharp, new string[] {
                        "Smoke"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify whether user sign by Basic plan")]
        [NUnit.Framework.CategoryAttribute("BasicPlanSigin")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserSignByBasicPlan(string username, string password, string url, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "BasicPlanSigin"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify whether user sign by Basic plan", null, @__tags);
#line 4
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
         testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
   testRunner.When("user clicks on DAshboard Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
   testRunner.When("user clicks on Settings and click on Account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
            testRunner.When("user clicks on Cancel Subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
            testRunner.When("user clicks on Transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify whether user click on \"Add Job\" and post Jobs by Basic plan with \"Single J" +
            "ob\"")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserClickOnAddJobAndPostJobsByBasicPlanWithSingleJob(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify whether user click on \"Add Job\" and post Jobs by Basic plan with \"Single J" +
                    "ob\"", null, exampleTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 20
          testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
             testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
             testRunner.Then("I try to Add job with single job Url and postjob", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
          testRunner.When("I Click on job description and enter value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
             testRunner.When("I click on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
          testRunner.When("I click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
    testRunner.Then("click on company for the Given Job Url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
          testRunner.When("click on Location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
             testRunner.When("I click on Valid Through based on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
          testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
          testRunner.Then("I click on OptimiZe Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
             testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
    testRunner.Then("I click on Edit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
          testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify whether user click on \"Add Job\" and post Jobs by Basic plan with \"Multiple" +
            " Job\"")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserClickOnAddJobAndPostJobsByBasicPlanWithMultipleJob(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify whether user click on \"Add Job\" and post Jobs by Basic plan with \"Multiple" +
                    " Job\"", null, exampleTags);
#line 39
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 40
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
         testRunner.Then("I click on Addjob", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 43
         testRunner.Then("Enter multiple Job and click on Postjobs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
         testRunner.Then("I click on popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
         testRunner.When("I click on symbols", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
         testRunner.Then("I click on preview", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user Create Job And \"Proceed\" through \"Continue with Original Page\"")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserCreateJobAndProceedThroughContinueWithOriginalPage(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user Create Job And \"Proceed\" through \"Continue with Original Page\"", null, exampleTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 54
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
            testRunner.When("user clicks on Change Source Link and enter all field clicks", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
            testRunner.When("user clicks on Add New Job and click on proceed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 58
   testRunner.When("user Enter All the Job details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
            testRunner.Then("user clicks on previewbutton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify user upload \"Job PDF\" by Basic plan")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserUploadJobPDFByBasicPlan(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify user upload \"Job PDF\" by Basic plan", null, exampleTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 68
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 69
            testRunner.When(string.Format("I try to login with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
         testRunner.Then("upload PDF By Plans", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 71
         testRunner.When("I Click on job description and enter value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
            testRunner.When("I click on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
         testRunner.When("I click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
      testRunner.Then("click on company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
            testRunner.Then("click on Salary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
   testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
        testRunner.Then("I click on OptimiZe Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 78
            testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 79
            testRunner.Then("I click on Edit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 80
            testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user Create Job And \"Proceed\" through \"Collecting Resumes\"")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserCreateJobAndProceedThroughCollectingResumes(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user Create Job And \"Proceed\" through \"Collecting Resumes\"", null, exampleTags);
#line 85
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 86
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 87
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
            testRunner.When("user clicks on Change Source Link and Select collect Resume", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
            testRunner.When("user clicks on Add New Job and click on proceed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
   testRunner.When("user Enter All the Job details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
         testRunner.Then("user clicks on previewbutton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user click on \"ATS\" and post the Job by \"Continue with Original Page\"")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void UserClickOnATSAndPostTheJobByContinueWithOriginalPage(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user click on \"ATS\" and post the Job by \"Continue with Original Page\"", null, exampleTags);
#line 99
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 100
      testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 101
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 102
   testRunner.Then("User click on ATS and JobDiva by Continue with Original Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 103
   testRunner.Then("User enter API keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
   testRunner.Then("User click on continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user click on \"ATS\" option and post the Job by \"Collecting Resumes\"")]
        [NUnit.Framework.TestCaseAttribute("ajay.mugada+4004@jobiak.com", "ajay1997", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserClickOnATSOptionAndPostTheJobByCollectingResumes(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user click on \"ATS\" option and post the Job by \"Collecting Resumes\"", null, exampleTags);
#line 109
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 110
      testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 111
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 112
            testRunner.Then("User click on ATS and JobDiva by Collecting Resumes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
   testRunner.Then("User enter API keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 114
   testRunner.Then("User click on continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

