// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDAutomation.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("EnterprisePlan")]
    [NUnit.Framework.CategoryAttribute("Smoke")]
    public partial class EnterprisePlanFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EnterprisePlan.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EnterprisePlan", null, ProgrammingLanguage.CSharp, new string[] {
                        "Smoke"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify whether user signup by Method 1 in Enterprise plan")]
        [NUnit.Framework.CategoryAttribute("EnterprisePlan")]
        [NUnit.Framework.TestCaseAttribute("mohan@jobiak.ai", "mohan@123", "https://support.jobiak.ai/login", "Method 1", "rinki14@jobiak.ai", null)]
        public virtual void VerifyWhetherUserSignupByMethod1InEnterprisePlan(string username, string password, string url, string methodName, string email, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EnterprisePlan"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify whether user signup by Method 1 in Enterprise plan", null, @__tags);
#line 4
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
   testRunner.Given(string.Format("user navigates to {0} for support dashboard page", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
   testRunner.When(string.Format("I try to login with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
   testRunner.When("User Click On CustomerOnboarding And CreateAccount", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
   testRunner.When(string.Format("Signin with {0} Email", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
   testRunner.Then("User Enter All BasicInformation Fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
   testRunner.Then("User Enter Company Informartion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
   testRunner.Then(string.Format("Click on methods {0} and save", methodName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify whether user signup by Method 2 in Enterprise plan")]
        [NUnit.Framework.TestCaseAttribute("mohan@jobiak.ai", "mohan@123", "https://support.jobiak.ai/login", "Method 2", "rinki17@jobiak.ai", null)]
        public virtual void VerifyWhetherUserSignupByMethod2InEnterprisePlan(string username, string password, string url, string methodName, string email, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify whether user signup by Method 2 in Enterprise plan", null, exampleTags);
#line 16
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 17
   testRunner.Given(string.Format("user navigates to {0} for support dashboard page", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
   testRunner.When(string.Format("I try to login with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
   testRunner.When("User Click On CustomerOnboarding And CreateAccount", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
   testRunner.When(string.Format("Signin with {0} Email", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
         testRunner.Then("User Enter All BasicInformation Fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
   testRunner.Then("User Enter Company Informartion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
   testRunner.Then(string.Format("Click on methods {0} and save", methodName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify whether user signup by Method 3 in Enterprise plan")]
        [NUnit.Framework.TestCaseAttribute("mohan@jobiak.ai", "mohan@123", "https://support.jobiak.ai/login", "Method 3", "rinki16@jobiak.ai", null)]
        public virtual void VerifyWhetherUserSignupByMethod3InEnterprisePlan(string username, string password, string url, string methodName, string email, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify whether user signup by Method 3 in Enterprise plan", null, exampleTags);
#line 28
   this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 29
   testRunner.Given(string.Format("user navigates to {0} for support dashboard page", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
   testRunner.When(string.Format("I try to login with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
   testRunner.When("User Click On CustomerOnboarding And CreateAccount", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
   testRunner.When(string.Format("Signin with {0} Email", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
         testRunner.Then("User Enter All BasicInformation Fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 34
   testRunner.Then("User Enter Company Informartion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 35
   testRunner.Then(string.Format("Click on methods {0} and save", methodName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify whether user click on \"Add Job\" and post Jobs by Enterprise plan with \"Sin" +
            "gle Job\"")]
        [NUnit.Framework.TestCaseAttribute("tejaswini@jobiak.ai", "Teju@123", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserClickOnAddJobAndPostJobsByEnterprisePlanWithSingleJob(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify whether user click on \"Add Job\" and post Jobs by Enterprise plan with \"Sin" +
                    "gle Job\"", null, exampleTags);
#line 40
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 41
          testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
             testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
             testRunner.Then("I try to Add job with single job Url and postjob", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
          testRunner.When("I Click on job description and enter value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
             testRunner.When("I click on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
          testRunner.When("I click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
    testRunner.Then("click on company for the Given Job Url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
          testRunner.When("click on Location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
             testRunner.When("I click on Valid Through based on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
          testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
          testRunner.Then("I click on OptimiZe Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
             testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
             testRunner.Then("I click on Edit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
          testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify whether user click on \"Add Job\" and post Jobs by Enterprise plan with \"Mul" +
            "tiple Job\"")]
        [NUnit.Framework.TestCaseAttribute("tejaswini@jobiak.ai", "Teju@123", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserClickOnAddJobAndPostJobsByEnterprisePlanWithMultipleJob(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify whether user click on \"Add Job\" and post Jobs by Enterprise plan with \"Mul" +
                    "tiple Job\"", null, exampleTags);
#line 59
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 60
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 61
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
      testRunner.Then("User click on ChangeSource and select Carrer Job Url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
         testRunner.Then("Enter multiple Job and click on Postjobs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
         testRunner.Then("I click on popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
         testRunner.When("I click on symbols", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
         testRunner.Then("I click on preview", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user Create Job And \"Proceed\"")]
        [NUnit.Framework.TestCaseAttribute("tejaswini@jobiak.ai", "Teju@123", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserCreateJobAndProceed(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user Create Job And \"Proceed\"", null, exampleTags);
#line 71
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 72
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
   testRunner.Then("User click on ChangeSource and select Carrer Job Url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
            testRunner.When("user clicks on Add New Job and click on proceed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
   testRunner.When("user Enter All the Job details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
         testRunner.Then("user clicks on previewbutton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user click on \"ATS\" option and post the Job")]
        [NUnit.Framework.TestCaseAttribute("tejaswini@jobiak.ai", "Teju@123", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserClickOnATSOptionAndPostTheJob(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user click on \"ATS\" option and post the Job", null, exampleTags);
#line 83
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 84
        testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
              testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
              testRunner.Then("User click on ATS and JobDiva", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 87
     testRunner.Then("User enter API keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 88
     testRunner.Then("User click on continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

