// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDAutomation.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HowWeWorkPartnershipsAlliances")]
    public partial class HowWeWorkPartnershipsAlliancesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HowWeWorkPartnershipsAlliances.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HowWeWorkPartnershipsAlliances", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("a)Verify Whether user click on \"how we work\" and click \"contact us to get started" +
            "\" to Register to Given plans")]
        [NUnit.Framework.CategoryAttribute("HowWeWorkPartnershipsAlliances")]
        [NUnit.Framework.TestCaseAttribute("https://www.jobiak.ai", null)]
        public virtual void AVerifyWhetherUserClickOnHowWeWorkAndClickContactUsToGetStartedToRegisterToGivenPlans(string url, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "HowWeWorkPartnershipsAlliances"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("a)Verify Whether user click on \"how we work\" and click \"contact us to get started" +
                    "\" to Register to Given plans", null, @__tags);
#line 3
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
                   testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
       testRunner.When("user clicks on How we Work", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
       testRunner.When("user clicks on Contact Us Get Started Button in How we Work Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("b)Verify Whether user click on \"partnerships\"  and click \"contact us to get start" +
            "ed\" to Register to Given plans")]
        [NUnit.Framework.TestCaseAttribute("https://www.jobiak.ai", null)]
        public virtual void BVerifyWhetherUserClickOnPartnershipsAndClickContactUsToGetStartedToRegisterToGivenPlans(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("b)Verify Whether user click on \"partnerships\"  and click \"contact us to get start" +
                    "ed\" to Register to Given plans", null, exampleTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 13
                      testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
       testRunner.When("user clicks on Partnerships", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
       testRunner.When("user clicks on Contact Us Get Started Button in Partnerships", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("a)Verify Whether user click on \"Strategic Alliances\" and click \"contact us to get" +
            " started\" to Register to Given plans")]
        [NUnit.Framework.TestCaseAttribute("https://www.jobiak.ai", null)]
        public virtual void AVerifyWhetherUserClickOnStrategicAlliancesAndClickContactUsToGetStartedToRegisterToGivenPlans(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("a)Verify Whether user click on \"Strategic Alliances\" and click \"contact us to get" +
                    " started\" to Register to Given plans", null, exampleTags);
#line 21
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 22
                   testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
       testRunner.When("user clicks on Strategic Alliances", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
       testRunner.When("user clicks Contact Us Get Started Button in StartAllainces", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

