// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDAutomation.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Pricing")]
    public partial class PricingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Pricing.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Pricing", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user clicks on \"Pricing\" and select \"Enterprise\" Plan1,plan2,plan3,plan4,p" +
            "lan5 and click on \"Contact Us To Get Started\"")]
        [NUnit.Framework.CategoryAttribute("Pricing")]
        [NUnit.Framework.TestCaseAttribute("https://www.jobiak.ai", null)]
        public virtual void VerifyUserClicksOnPricingAndSelectEnterprisePlan1Plan2Plan3Plan4Plan5AndClickOnContactUsToGetStarted(string url, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Pricing"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user clicks on \"Pricing\" and select \"Enterprise\" Plan1,plan2,plan3,plan4,p" +
                    "lan5 and click on \"Contact Us To Get Started\"", null, @__tags);
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
         testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
   testRunner.When("user clicks on Pricing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
         testRunner.When("user selects on Enterprise Plan 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
         testRunner.When("user clicks on Contact Us Get Started", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
         testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
         testRunner.When("user selects  Enterprise and click Plan 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
         testRunner.When("user clicks on Contact Us Get Started", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
         testRunner.When("user selects on Enterprise and click on plan 3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
         testRunner.When("user clicks on Contact Us Get Started", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
         testRunner.When("user selects and clicks on Enterprise Plan 4", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
         testRunner.When("user clicks on Contact Us Get Started", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
         testRunner.When("user selects Enterprise Plan 5 and click on Contact US Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
   testRunner.When("user clicks on Contact Us Get Started", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
   testRunner.Then("user Enter contact page Fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user clicks on \"Pricing\" and select \"SMB\" Basic,pro,Feature plans and clic" +
            "k on \"TRY IT NOW\"")]
        [NUnit.Framework.TestCaseAttribute("https://www.jobiak.ai", null)]
        public virtual void VerifyUserClicksOnPricingAndSelectSMBBasicProFeaturePlansAndClickOnTRYITNOW(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user clicks on \"Pricing\" and select \"SMB\" Basic,pro,Feature plans and clic" +
                    "k on \"TRY IT NOW\"", null, exampleTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 27
         testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
   testRunner.When("user clicks on Pricing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
         testRunner.When("user selects and clicks on Small medium Business", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
   testRunner.When("User click on SMBS Basic plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
         testRunner.When("user click on Basic TRY IT NOW", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
         testRunner.When("User click on SMBS Pro plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
         testRunner.When("user selects PRO plan and click on TRY IT NOW", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
         testRunner.When("User click on SMBS Feature plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
         testRunner.When("user Selects Feature plan and click on TRY IT NOW", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
   testRunner.When("User click on SMBS Basic plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
         testRunner.When("user clicks on Basicplan and click on START POSTING", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 42
         testRunner.When("User click on SMBS Pro plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
         testRunner.When("user clicks on PRO plan and click on START POSTING", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
   testRunner.Then("Navigate Back to Given Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
         testRunner.When("User click on SMBS Feature plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
         testRunner.When("user clicks on Feature plan and click on START POSTING", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user clicks on \"Partnerships\" and click on \"Contact Us To Get Started\"")]
        [NUnit.Framework.TestCaseAttribute("https://www.jobiak.ai", null)]
        public virtual void VerifyUserClicksOnPartnershipsAndClickOnContactUsToGetStarted(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user clicks on \"Partnerships\" and click on \"Contact Us To Get Started\"", null, exampleTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 53
         testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
   testRunner.When("user clicks on Pricing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
         testRunner.When("User click on Partnerships", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
   testRunner.When("User click on Partnerships Link and click on contact us Get Started", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user clicks on \"About\" and click on \"Start Posting\"")]
        [NUnit.Framework.TestCaseAttribute("https://www.jobiak.ai", null)]
        public virtual void VerifyUserClicksOnAboutAndClickOnStartPosting(string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user clicks on \"About\" and click on \"Start Posting\"", null, exampleTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 64
         testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
   testRunner.When("User click on About Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
   testRunner.When("User click on About Link and Start Posting", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

