// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BDDAutomation.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ProPlanSigin")]
    [NUnit.Framework.CategoryAttribute("Smoke")]
    public partial class ProPlanSiginFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ProPlanSigin.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ProPlanSigin", null, ProgrammingLanguage.CSharp, new string[] {
                        "Smoke"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify whether user sign by Pro plan")]
        [NUnit.Framework.CategoryAttribute("ProPlanSigin")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserSignByProPlan(string username, string password, string url, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ProPlanSigin"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify whether user sign by Pro plan", null, @__tags);
#line 4
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
         testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
   testRunner.When("user clicks on DAshboard Link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
   testRunner.When("user clicks on Settings and click on Account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
         testRunner.When("user clicks on Cancel Subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
            testRunner.When("user clicks on Transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify whether user click on \"Add Job\" and post Jobs by Pro plan with \"Single Job" +
            "\"")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserClickOnAddJobAndPostJobsByProPlanWithSingleJob(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify whether user click on \"Add Job\" and post Jobs by Pro plan with \"Single Job" +
                    "\"", null, exampleTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 20
          testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
             testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
             testRunner.Then("I try to Add job with single job Url and postjob", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
          testRunner.When("I Click on job description and enter value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
             testRunner.When("I click on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
          testRunner.When("I click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
    testRunner.Then("click on company for the Given Job Url", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
          testRunner.When("click on Location", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
             testRunner.When("I click on Valid Through based on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
          testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
          testRunner.Then("I click on OptimiZe Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
             testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
             testRunner.Then("I click on Edit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
          testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify whether user click on \"Add Job\" and post Jobs by Pro plan with \"Multiple J" +
            "ob\" url")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyWhetherUserClickOnAddJobAndPostJobsByProPlanWithMultipleJobUrl(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify whether user click on \"Add Job\" and post Jobs by Pro plan with \"Multiple J" +
                    "ob\" url", null, exampleTags);
#line 38
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 39
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 40
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
         testRunner.Then("I click on Addjob", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 42
         testRunner.Then("Enter multiple Job and click on Postjobs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 43
         testRunner.Then("I click on popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
         testRunner.When("I click on symbols", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
         testRunner.Then("I click on preview", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user Create Job And \"Proceed\" through \"Continue with Original Page\"")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserCreateJobAndProceedThroughContinueWithOriginalPage(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user Create Job And \"Proceed\" through \"Continue with Original Page\"", null, exampleTags);
#line 50
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 51
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
            testRunner.When("user clicks on Add New Job", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
   testRunner.When("user Enter All the Job details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
         testRunner.Then("user clicks on previewbutton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("verify user upload \"Job PDF\" by Pro plan")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserUploadJobPDFByProPlan(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify user upload \"Job PDF\" by Pro plan", null, exampleTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 61
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
            testRunner.When(string.Format("I try to login with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
         testRunner.Then("upload PDF By Plans", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
         testRunner.When("I Click on job description and enter value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
            testRunner.When("I click on Date Posted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
         testRunner.When("I click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
      testRunner.Then("click on company", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
            testRunner.Then("click on Salary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 69
   testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 70
        testRunner.Then("I click on OptimiZe Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 71
            testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 72
            testRunner.Then("I click on Edit Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
            testRunner.Then("I Click on Preview Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user Create Job And \"Proceed\" through \"Collecting Resumes\"")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserCreateJobAndProceedThroughCollectingResumes(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user Create Job And \"Proceed\" through \"Collecting Resumes\"", null, exampleTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 79
            testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
            testRunner.When("user clicks on Change Source Link and Select collect Resume", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 82
            testRunner.When("user clicks on Add New Job and click on proceed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
   testRunner.When("user Enter All the Job details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
         testRunner.Then("user clicks on previewbutton", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("user click on \"ATS\" and post the Job by \"Continue with Original Page\"")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void UserClickOnATSAndPostTheJobByContinueWithOriginalPage(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("user click on \"ATS\" and post the Job by \"Continue with Original Page\"", null, exampleTags);
#line 92
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 93
      testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 94
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 95
   testRunner.Then("User click on ATS and JobDiva by Continue with Original Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 96
   testRunner.Then("User enter API keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 97
   testRunner.Then("User click on continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify user click on \"ATS\" option and post the Job by \"Collecting Resumes\"")]
        [NUnit.Framework.TestCaseAttribute("venkatasai.nutheti+1052@jobiak.com", "Sai@7596", "https://app.jobiak.ai/login", null)]
        public virtual void VerifyUserClickOnATSOptionAndPostTheJobByCollectingResumes(string username, string password, string url, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify user click on \"ATS\" option and post the Job by \"Collecting Resumes\"", null, exampleTags);
#line 102
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 103
      testRunner.Given(string.Format("user navigates to {0} Jobiak URL site", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 104
            testRunner.When(string.Format("I Try to Signin with credentials {0} and {1}", username, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
            testRunner.Then("User click on ATS and JobDiva by Collecting Resumes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
   testRunner.Then("User enter API keys", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 107
   testRunner.Then("User click on continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

